### ISSUE TITLE
class calls don't work on cori with default intel compiler

### ISSUE THREAD

**Issue by pmcdonal** [adematti/pyclass#1]
This probably isn't fundamentally a pyclass problem - I think the python classy part of isolated class installation has similar problems. 
Even with CC=cc,  final creation of classy .so file seems to use gcc, but that can work and you still run into runtime problem of not finding needed libraries, possibly because of GCCPATH stuff in class/python/setup.py
(easier to just try it than me describe in detail here) 
Tried switching to all gcc, but intel is significantly faster, and seems this should be fixable (I will try eventually, but non-critical right now).

**Comment by adematti** [comment]
Hi, I haven't tried yet (will do asap), but is this similar to: https://github.com/lesgourg/class_public/issues/337?

**Comment by pmcdonal** [comment]
Yes.

**Comment by adematti** [comment]
Based on https://github.com/lesgourg/class_public/issues/40, last commit ecb7f5205a5e7e060f35d66f56908784846e5c1d should allow for automatic installation of pyclass. Using gcc at the link step should not be a concern. If you really want to use icc here, you can just export LDSHARED="icc -shared".

> Tried switching to all gcc, but intel is significantly faster

Have you witnessed a significant acceleration of CLASS with icc compared to gcc? CLASS developers wrote it did not make much difference.

**Comment by pmcdonal** [comment]
It works with pip install (had the failure to find library problem still when I tried to devel install, but I'll worry about that if I ever need to). 
It was the power spectrum code that is faster with intel. I (vaguely) think this has generally been my experience in the past, but never know without checking.
